### ISSUE TITLE
RESTer does not work with Firefox 71

### ISSUE THREAD

**Issue by k-c13** [frigus02/RESTer#115] opened 2019-12-06 08:35 UTC
Hi!

After the update to the last version of Firefox RESTer does not work

Downgrade to Firefox 70.0.1 it works again.

Using Firefox 64bit on Linux

CU
  Michael

**Comment by DaWe35** [comment] 2019-12-09 16:23
For me, POST parameters sent as GET params:

**Comment by frigus02** [comment] 2019-12-29 10:26
Sorry for the delayed response.

Hi @k-c13, I don't seem to be able to reproduce the issue. Can you describe what doesn't work? Does RESTer fail to load, are requests not send correctly or something else?

@DaWe35, this looks like the intended bahaviour. Even POST requests can contain query parameters in the URL. If you want to send parameters in the body tab. You can change switch the body to "Form" to see similar input fields.

![grafik](https://user-images.githubusercontent.com/3579251/71555559-13f66b00-2a2e-11ea-9cc6-f974aedcb6b7.png)

**Comment by frigus02** [comment] 2020-05-06 19:37
I'm going to close this for now. But please feel free to reopen if this is still an issue.

**Closed by frigus02** 2020-05-06 19:37 UTC
