### ISSUE TITLE
Broken plugin because of Angular error

### ISSUE THREAD

**Issue by Buzut** [frigus02/RESTer#10] opened 2016-05-24 17:37 UTC
Hi, 
The plugin doesn't work any more (see screenshot)
![capture d ecran 2016-05-24 a 19 35 33](https://cloud.githubusercontent.com/assets/6450536/15513865/b3e22644-21e6-11e6-80c0-11136a0cdc46.png)

FF 46.0.1 on Mac OS 10.11.4

The error in the console:

    SyntaxError: missing : after property id lint-inspections.js:49:61
    mal formé main.html:1:11
    mal formé main.request.html:2:37
    "Error: [$injector:unpr] http://errors.angularjs.org/1.5.5/$injector/unpr?p0=%24lintInspectionsProvider%20%3C-%20%24lintInspections%20%3C-%20RequestCtrl
    O/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:6:412
    bb/m.$injector<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:43:84
    d@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:40:344
    bb/M<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:43:144
    d@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:40:344
    e@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:41:78
    h/<.instantiate@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:41:441
    ef/this.$get</<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:89:307
    z/<.compile/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/ui-router/release/angular-ui-router.min.js:7:23742
    ja@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:80:350
    n@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:66:28
    g@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:58:305
    ba/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:57:455
    Yb/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:62:279
    k@resource://rester-at-kuehle-dot-me/data/site/bower_components/ui-router/release/angular-ui-router.min.js:7:23132
    y/k.compile/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/ui-router/release/angular-ui-router.min.js:7:23409
    ja@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:80:350
    n@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:66:28
    g@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:58:305
    n@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:65:473
    g@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:58:305
    n@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:65:473
    g@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:58:305
    n@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:65:473
    g@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:58:305
    ba/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:57:455
    z/<.compile/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/ui-router/release/angular-ui-router.min.js:7:23887
    ja@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:80:350
    n@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:66:28
    g@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:58:305
    ba/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:57:455
    Yb/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:62:279
    k@resource://rester-at-kuehle-dot-me/data/site/bower_components/ui-router/release/angular-ui-router.min.js:7:23132
    y/k.compile/</<@resource://rester-at-kuehle-dot-me/data/site/bower_components/ui-router/release/angular-ui-router.min.js:7:23401
    tf/this.$get</n.prototype.$broadcast@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:147:327
    v/y.transitionTo/y.transition<@resource://rester-at-kuehle-dot-me/data/site/bower_components/ui-router/release/angular-ui-router.min.js:7:18767
    e/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:130:226
    tf/this.$get</n.prototype.$eval@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:144:463
    tf/this.$get</n.prototype.$digest@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:142:39
    tf/this.$get</n.prototype.$apply@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:145:247
    l@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:97:53
    H@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:101:190
    dg/</u.onload@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:102:229
    " <div flex="" layout="column" class="main-content ng-scope" ui-view=""> angular.min.js:117:210
    e/<() angular.min.js:117
    gf/this.$get</<() angular.min.js:89
    ja() angular.min.js:80
    n() angular.min.js:66
    g() angular.min.js:58
    ba/<() angular.min.js:57
    Yb/<() angular.min.js:62
    k() angular-ui-router.min.js:7
    y/k.compile/<() angular-ui-router.min.js:7
    ja() angular.min.js:80
    n() angular.min.js:66
    g() angular.min.js:58
    n() angular.min.js:65
    g() angular.min.js:58
    n() angular.min.js:65
    g() angular.min.js:58
    n() angular.min.js:65
    g() angular.min.js:58
    ba/<() angular.min.js:57
    z/<.compile/<() angular-ui-router.min.js:7
    ja() angular.min.js:80
    n() angular.min.js:66
    g() angular.min.js:58
    ba/<() angular.min.js:57
    Yb/<() angular.min.js:62
    k() angular-ui-router.min.js:7
    y/k.compile/</<() angular-ui-router.min.js:7
    tf/this.$get</n.prototype.$broadcast() angular.min.js:147
    v/y.transitionTo/y.transition<() angular-ui-router.min.js:7
    e/<() angular.min.js:130
    tf/this.$get</n.prototype.$eval() angular.min.js:144
    tf/this.$get</n.prototype.$digest() angular.min.js:142
    tf/this.$get</n.prototype.$apply() angular.min.js:145
    l() angular.min.js:97
    H() angular.min.js:101
    dg/</u.onload() angular.min.js:102

    mal formé navigation-list.html:40:24
    "Error: [$injector:unpr] http://errors.angularjs.org/1.5.5/$injector/unpr?p0=%24lintInspectionsProvider%20%3C-%20%24lintInspections%20%3C-%20RequestCtrl
    O/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:6:412
    bb/m.$injector<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:43:84
    d@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:40:344
    bb/M<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:43:144
    d@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:40:344
    e@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:41:78
    h/<.invoke@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:41:163
    ef/this.$get</</<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:89:201
    n@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:64:374
    aa/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:76:290
    e/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:130:226
    tf/this.$get</n.prototype.$eval@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:144:463
    tf/this.$get</n.prototype.$digest@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:142:39
    tf/this.$get</n.prototype.$apply@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:145:247
    l@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:97:53
    H@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:101:190
    dg/</u.onload@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:102:229
    " angular.min.js:117:210
    e/<() angular.min.js:117
    gf/this.$get</<() angular.min.js:89
    e/<() angular.min.js:130
    tf/this.$get</n.prototype.$eval() angular.min.js:144
    tf/this.$get</n.prototype.$digest() angular.min.js:142
    tf/this.$get</n.prototype.$apply() angular.min.js:145
    l() angular.min.js:97
    H() angular.min.js:101
    dg/</u.onload() angular.min.js:102

    mal formé url-input.html:1:37
    données incompréhensibles après l'élément de document highlight-code.html:2:1

**Comment by frigus02** [comment] 2016-05-24 18:17
Duplicate of #8. Fix is already uploaded in version 1.9.1.

**Closed by frigus02** 2016-05-24 18:17 UTC
