### ISSUE TITLE
Cursor jumps to end when changing URL structure

### ISSUE THREAD

**Issue by maffe** [frigus02/RESTer#40] opened 2017-08-17 12:25 UTC
Steps to reproduce:
* Enter URL `https://localhost/a?b`
* Select `?`
* Replace the `?` with a `/` (or change it back to `?`)

Then the cursor jumps to the end of the URL, making editing harder than it should be.

**Comment by frigus02** [comment] 2017-08-17 16:00
Thanks for reporting. This is clearly a bug. It's caused by the same thing like #38, which is fixed in master. I plan to release an update on the weekend.

**Comment by frigus02** [comment] 2017-09-21 18:56
That's fixed in the newest update 3.0.0.

**Closed by frigus02** 2017-09-21 18:56 UTC
Labels: bug
