### ISSUE TITLE
Large responses crash Firefox 

### ISSUE THREAD

**Issue by Bilge** [frigus02/RESTer#9] opened 2016-05-24 13:13 UTC
Responses upwards of ~2500 lines consistently crash Firefox. Other REST clients solve this by automatically disabling syntax highlighting for responses over a given threshold.

**Comment by frigus02** [comment] 2016-05-24 17:03
I will have a look on this at the weekend. Disabling syntax highlighting is probably a good idea for such large responses.

**Comment by frigus02** [comment] 2016-05-26 14:50
@Bilge could you tell me more about your data? I want to make sure my solution will work for you. Do you have JSON, XML? How long are the lines? Can you measure the size of the response in KB/MB?

**Comment by Bilge** [comment] 2016-05-26 14:50
The data is private.

**Comment by frigus02** [comment] 2016-05-26 14:52
Sure, I don't want your data. I just want to know the format and size in bytes, so I can generate similar sample data for testing.

**Comment by Bilge** [comment] 2016-05-26 15:06
I would suggest it is more useful to generate a wide variety of data in
order to capture all cases and not just my specific case.

**Comment by Bilge** [comment] 2016-05-31 17:51
This should not be closed because it just adds a button that warns about displaying the response. Clicking it still crashes the browser. It is useless to have a REST client that offers you the option of not seeing the response. If I didn't want to see the response I usually wouldn't need a REST client.

**Comment by frigus02** [comment] 2016-05-31 18:48
This does not just add a button. It improved the handling of large responses in general. Coud you please provide a bit more details about your response (format and size in bytes). I can't reproduce a crash. For me the browser does get very slow and sometimes hangs for a few seconds when the response is very large. But even 5 MB of JSON it is working fine.

**Comment by frigus02** [comment] 2016-12-21 15:59
New versions starting from 1.16.0 use [Ace](http://ace.c9.io/) to render the response, which uses virtual scrolling. I don't see how we could get any better now. So I'm closing this issue until someone comes up with a better solution.

**Closed by frigus02** 2016-12-21 15:59 UTC
