### ISSUE TITLE
RESTer always display content-type text/plain as a normal form

### ISSUE THREAD

**Issue by DaxMX** [frigus02/RESTer#410] opened 2021-06-24 00:30 UTC
Time to time while I'd created a new request and set it's header Content-Type to text/plain, the next time I open this request RESTer will change the BODY section to a regular form and ASK to set Content-Type header to application/x-www-form-urlencoded, this is very annoying.

Since RESTer have and option to set the body to a PLAIN, it should honor the Conten-Type text/plain declared in the header section.

Just now RESTer honor the content-type json header to render the body section, but some applications ask for a TEXT/PLAIN header for json data or content-type: my-personalized/type.

This is an ilustrated example to clarify all my writen words:
1- Create a new text/plain request:
![rester-text-plain-fail-1](https://user-images.githubusercontent.com/82778475/123184004-66b0b780-d458-11eb-84ad-7c7c72346e3b.png)
![rester-text-plain-fail-2](https://user-images.githubusercontent.com/82778475/123184033-73cda680-d458-11eb-9fb4-14d6088f724b.png)
2- Visit any other request and back again to the text/plain request, you will seed this 🙄
![rester-text-plain-fail-3](https://user-images.githubusercontent.com/82778475/123184140-b1caca80-d458-11eb-81e1-42d52bb03e11.png)

A possible Fix is to save the TYPE selectected when the request is created, just like the URL, headers, etc. are saved, and the next time the request is opened RESTer should render the body page as it was originally saved.
![rester-text-plain-fail-4](https://user-images.githubusercontent.com/82778475/123184194-cc9d3f00-d458-11eb-9a83-59c4fda13205.png)

Anyway, thank you for RESTer, it's really really great and useful.

**Comment by frigus02** [comment] 2021-06-24 08:09
Thanks @DaxMX for the detailed report. I can reproduce this when in "2- Visit any other request" I visit a request that has a form body.

I agree this is super annoying. Will try to fix that 🙂

**Comment by frigus02** [comment] 2021-06-24 08:27
You're probably right with your suggestion, that the best fix would save the select body input method for each request.

Currently RESTer looks at the Content-Type header, but it doesn't understand `text/plain`. I'm going to make it understand `text/plain` for now because it's easier to implement. If there are still annoyances, I might implement your suggested fix later on.

**Comment by frigus02** [comment] 2021-06-24 09:52
Fix is released in 4.7.0. Should be available in the next hours.

**Closed by frigus02** 2021-06-24 09:52 UTC
Labels: bug
