### ISSUE TITLE
Import & Export features

### ISSUE THREAD

**Issue by fcestrada** [frigus02/RESTer#12] opened 2016-06-20 23:50 UTC
Hi Jan,

First of all thank you so much for your hard work in this app :smile: . I work in a team so it's very common to share many saved tests with colleagues, so, can you please consider to add import & export features? :pray: 

Thanks in advance for your attention regarding this request. :wink: 

Best Regards,

**Comment by frigus02** [comment] 2016-06-21 20:07
Hi. Import/Export is definitely something I plan to add. However I don't have a clear vision yet how to do this properly.

Just to get some insights: Would you prefer import/export to a local file on your PC or to a cloud service like Google Drive?

**Comment by fcestrada** [comment] 2016-06-24 00:29
Hi Jan,

At this moment the request is very simple, just an option to export and import from/to a local file would be awesome :wink:

Thanks a lot for your attention regarding this request!!!

Best regards,

**Comment by pmdhaussy** [comment] 2016-07-26 08:17
Hi guys.

It could be sweet to handle HAR and json postman format for export.

@frigus02 Great addon. I love it !

**Comment by frigus02** [comment] 2016-07-26 16:01
@pmdhaussy Thanks for the hint, this is a good point. Export (and probably also import) format should be compatible to the other available tools (most notably Postman).

**Comment by frigus02** [comment] 2017-06-20 17:39
The Postman JSON schema seems to be really nice. It's documented here: https://schema.getpostman.com/

**Comment by michelkaeser** [comment] 2017-08-04 07:32
👍

**Comment by frigus02** [comment] 2018-02-10 21:07
I just uploaded version 3.7.0, which has support Import & Export of requests in Postman Collection Format.

**Comment by gigaSproule** [comment] 2018-04-04 16:39
Import works really well, but would be perfect if it could replace `{{variable}}` with `{$env.variable}`

**Comment by frigus02** [comment] 2018-04-04 18:57
Yep, support for variables would be great.

I can't spend as much time on RESTer at the moment as I would like to. So if anyone wants to have a look at this, a PR is very welcome. Just drop a quick comment here to let me know you are working on it.

**Comment by frigus02** [comment] 2018-09-24 10:19
Hey @willy666rumster, sorry for the late response. After clicking on export, you should get a file picker dialog, allowing you to choose the location. I assume the dialog doesn't appear for you. Would you mind checking the dev tools console for errors? Also, can you send me your browser version and RESTer version you are using?

**Comment by willy666rumster** [comment] 2018-09-26 01:48
Hey, @frigus02, thank you for response.
Yes, the file picker dialog doesn't appear for me. Just disappearing a format dialog, when I clicking on export.
I use Android 4.4.0
FireFox 62.0.1
RESTer version 3.9.0

Libraries and frameworks:
ace-builds 1.3.3
dompurify 1.0.5
frigus02/vkBeautify 1.0.1
joshaven/string_score 0.1.22
mousetrap 1.6.2
paper-subheader 2.0.2
Polymer/polymer 2.6.0
PolymerElements/app-layout 2.1.1
PolymerElements/app-route 2.1.1
PolymerElements/font-roboto-local 1.0.1
PolymerElements/iron-a11y-keys 2.1.2
PolymerElements/iron-collapse 2.2.1
PolymerElements/iron-flex-layout 2.0.3
PolymerElements/iron-form 2.3.0
PolymerElements/iron-icon 2.1.0
PolymerElements/iron-iconset-svg 2.2.1
PolymerElements/iron-input 2.1.3
PolymerElements/iron-media-query 2.1.0
PolymerElements/iron-pages 2.1.1
PolymerElements/iron-selector 2.1.0
PolymerElements/neon-animation 2.2.1
PolymerElements/paper-badge 2.1.0
PolymerElements/paper-button 2.1.1
PolymerElements/paper-checkbox 2.0.4
PolymerElements/paper-dialog 2.1.1
PolymerElements/paper-dialog-scrollable 2.2.1
PolymerElements/paper-dropdown-menu 2.1.0
PolymerElements/paper-fab 2.1.0
PolymerElements/paper-icon-button 2.2.0
PolymerElements/paper-input 2.2.2
PolymerElements/paper-item 2.1.1
PolymerElements/paper-listbox 2.1.1
PolymerElements/paper-menu-button 2.1.1
PolymerElements/paper-progress 2.1.1
PolymerElements/paper-radio-button 2.1.0
PolymerElements/paper-radio-group 2.2.0
PolymerElements/paper-slider 2.0.6
PolymerElements/paper-spinner 2.1.0
PolymerElements/paper-styles 2.1.0
PolymerElements/paper-tabs 2.1.1
PolymerElements/paper-toggle-button 2.1.1
PolymerElements/paper-tooltip 2.1.1
web-animations/web-animations-js 2.3.1
webcomponents/webcomponentsjs b5af6a76a5b7dd4a7183f0fd2b646f76e6a2a02d

**Comment by frigus02** [comment] 2018-09-27 19:58
Thanks for the info. I can reproduce this on Android. Will track this bug separately under #76.

**Comment by frigus02** [comment] 2019-06-24 20:06
I'm going to close this and track improvements to import/export in separate issues:
- Environments: #95

**Closed by frigus02** 2019-06-24 20:06 UTC
Labels: enhancement
