### ISSUE TITLE
origin header mandatorily added to the request header

### ISSUE THREAD

**Issue by fwonce** [frigus02/RESTer#75] opened 2018-09-25 11:03 UTC
When sending a request in Firefox, an 'origin' header will be mandatorily added to this request, with a value which is something like `moz-extension://049e9a01-cbcb-e64b-92b9-5b431570fef5`.
Even when I explicitly set one, the value above will still be prepended in the 'origin' line, separated from the given one with a comma. This behavior stops me from testing APIs that strictly follow the CORS policy in Firefox.
I also found out that this doesn't happen in Chrome at all. And many other REST clients in Firefox have the same problem. I'm wondering whether it's due to Firefox's built-in mechanism.

**Comment by frigus02** [comment] 2018-09-27 19:53
Thanks for the report. I will try to fix this in the next update. In the mean time, you can use a workaround:

When you change the request mode to "Clean requests" in the settings (the gear icon in the left panel), RESTer will try to only send the headers you explicitly specify. This will also remove things like the user agent. But it should only send the specified origin header.

**Comment by fwonce** [comment] 2018-09-28 02:46
Thanks for the reply. I understand the workaround, but in my case, I still need the normal mode because manually adding the required cookie header which can be different from time to time is rather tedious to me. So I'll stick to the Chrome version which works perfectly for now. That said, as a Firefox person, I'll be more than happy if this is fixed. Thanks in advance!

**Comment by frigus02** [comment] 2018-12-18 17:37
Fixed in version 3.9.1. Sorry it took me so long to release this.

**Comment by walterstypula** [comment] 2020-03-13 14:16
It looks like this issue has returned as of Chrome: Version 80.0.3987.132 (Official Build) (64-bit).
I've tried the "Clean Requests" and it continues to include the extra headers and does not overwrite Origin.

![image](https://user-images.githubusercontent.com/1973060/76628730-96fa6e00-6513-11ea-8901-2534943f6c0c.png)

![image](https://user-images.githubusercontent.com/1973060/76628714-8e099c80-6513-11ea-8fba-b6947ad93c47.png)

**Comment by frigus02** [comment] 2020-03-14 16:26
Thanks for reporting. I'm going to track this as a new issue #122

**Comment by GennadyM73** [comment] 2022-01-06 21:50
It looks like the issue returned in Firefox.

I am trying to generate Oauth2 token but it says
-----
Ups, something went wrong!

Error: Access token error: invalid_request. Description: AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type. Trace ID: 9b8003cc-8c8e-40e0-927c-004b3eaf3601 Correlation ID: c42ba50f-7105-4058-838f-a9a06c6d4be6 Timestamp: 2022-01-06 21:20:56Z URI: https://login.microsoftonline.com/error?code=9002326
-----

'Clean requests' mode is enabled but the 'Origin' header is still in place...

> POST /70b6c650-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/token HTTP/1.1
> Host: login.microsoftonline.com
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0
> Accept: application/json
> Accept-Language: en-US,en;q=0.5
> Accept-Encoding: gzip, deflate, br
> authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> content-type: application/x-www-form-urlencoded
> Origin: moz-extension://84c680ef-a0f2-40ce-8a6c-7140c4ac47f2
> Content-Length: 83
> Connection: keep-alive
> Sec-Fetch-Dest: empty
> Sec-Fetch-Mode: cors
> Sec-Fetch-Site: same-origin
> Pragma: no-cache
> Cache-Control: no-cache

In developer tools I see that request fails with 
> Status: 400 Bad Request
> Version: HTTP/1.1
> Transferred: 1.27 KB (532 B size)
> Referrer Policy: strict-origin-when-cross-origin

If I re-send the same request by 'Developer Tools' without Origin header, then I receive the token successfully.

It worked for me fine for a long time but it stopped working one week ago. Probably it is related to Firefox upgrade.
I use Firefox 95.0.2 (64-bit), Add-on Version 4.8.0
Same issue in Firefox developer edition 96.0b10 (64-bit), Add-on Version 4.8.0

**Comment by frigus02** [comment] 2022-01-23 09:07
Sorry for the late reply. I have seen an added Origin header recently, too. But I can't reproduce it anymore in Firefox 96.0.2. Does that still happen for you?

**Comment by GennadyM73** [comment] 2022-01-24 14:50
Unfortunately it is still doesn't work for me in 96.0.2 (64bit).
Same error message.

**Comment by frigus02** [comment] 2022-01-24 18:55
Hm yeah. Not sure what I was doing yesterday. I can reproduce it now. I can reproduce it now. Not sure if RESTer can do anything. I'm going to take another look.

**Comment by frigus02** [comment] 2022-01-29 09:29
Okay, this is super weird. I can't reproduce it anymore. Tried today with the following setup:

- Windows 11
- Firefox 96.0.3 (64-Bit)
- RESTer 4.8.2
- Request mode: clean
- Request: `POST http://127.0.0.1:7373/echo` with `Content-Type` header and `foo=bar` body

Result:

```
POST /echo HTTP/1.1
Host: 127.0.0.1:7373
Content-Type: application/x-www-form-urlencoded
Content-Length: 7
Pragma: no-cache
Cache-Control: no-cache

foo=bar
```

I'm pretty sure I tried the same thing 5 days ago and the Origin header was there. Maybe that was with Firefox 96.0.2?

**Comment by GennadyM73** [comment] 2022-02-18 09:09
Now everything works fine for me as well in
Firefox 97.0,1 (64bit) with RESTer 4.9.0
Windows 10

Also I have 
Firefox Developer edition 98.0b3 (64-bit) with RESTer 4.9.0 (on the same PC).
And here I have issues with OAuth2 token generation via RESTer Authorization tab.
Error: Access token error: invalid_request. Description: AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type....

in request headers i see
Origin: moz-extension://84c680ef-a0f2-40ce-8a6c-7140c4ac47f2

If I send the same token request as a separate POST request (not via RESTer Authorization tab) then it works fine (No Origin header in request headers in this case).

**Comment by frigus02** [comment] 2022-02-19 10:01
Thanks for the details. I think I may have to open an issue with Firefox and ask for clarification. I'm not sure how to debug this properly at the moment.

**Comment by GennadyM73** [comment] 2022-03-18 17:04
@frigus02 ,
I noticed the following interesting behavior:

Request mode: clean

If I open a new RESTer tab and try to do OAuth2 authorization via RESTer Authorization tab, then it fails because Origin header is present in request headers. After this request all other requests I do in RESTer (even not related to Authorization tab), have Origin header.

But if I open a new RESTer tab and first do ANY request NOT via RESTer Authorization tab, then after that everything works fine (no Origin header) including authorization requests via RESTer Authorization tab.

**Comment by frigus02** [comment] 2022-03-18 17:35
Thank you, @GennadyM73. This is a great find. I think I know what's happening. My guess is that https://github.com/frigus02/RESTer/commit/8ad37946b5bd42fef6deb88278f47f2c5de08c41 broke this. Since then extension permissions required to control these headers is only requested on first use. But if the OAuth2 flow happens to be the first use, then it's not part of a user interaction and fails.

**Comment by frigus02** [comment] 2022-03-18 17:39
I'm having trouble reproducing this. But I want to make a release anyway, so I'm just going to include an attempt to fix this and hope it works. 🙂 🤞

**Comment by frigus02** [comment] 2022-03-18 17:52
I released version 4.9.1, which includes the attempted fix from #630. It should be available in the next few hours.

**Comment by GennadyM73** [comment] 2022-03-21 07:16
hi @frigus02 , 
now it works fine!
Thank you for fix and for good add-on!

**Comment by frigus02** [comment] 2022-03-21 07:21
No worries. Thank you for confirming and thanks for your help tracking this down.

**Closed** 2022-03-21 07:21 UTC
Labels: bug
