### ISSUE TITLE
Keeps throwing type error, and i'm lost on the reason why.

### ISSUE THREAD

**Issue by alvissraghnall** [frigus02/RESTer#619] opened 2022-02-28 06:37 UTC
Downloaded the extension to test my REST APIs, and it worked for the first few times.

However, subsequently, it threw errors: "TypeError: o.info is null", and i do not understand why. I've tested the request in a blank window and it executed successfully ( a basic GET request).

These are the details it shows(if it helps?):
transaction/r.execute/</s</<@moz-extension://e0d37654-4751-469e-a564-c112f105db40/background/bundle.js:1:1798
transaction/r.execute/</s<@moz-extension://e0d37654-4751-469e-a564-c112f105db40/background/bundle.js:1:1681
transaction/r.execute/<@moz-extension://e0d37654-4751-469e-a564-c112f105db40/background/bundle.js:1:1585
_withWriteLock/t/<@moz-extension://e0d37654-4751-469e-a564-c112f105db40/background/bundle.js:1:3025
t@moz-extension://e0d37654-4751-469e-a564-c112f105db40/background/bundle.js:1:2973

**Comment by frigus02** [comment] 2022-02-28 18:43
Oh no. That sounds like the data storage got corrupted. I've not seen this happen before. If you don't have much data stored, you might want to try to uninstall and re-install RESTer (possibly also restarting the browser in between). That should clear the data storage and start fresh.

I'd also like to find out how this happened. Are you using Chrome or Firefox?

**Comment by frigus02** [comment] 2022-06-06 15:24
Closing, because I'm unable to reproduce. Feel free to reopen if it still occurs.

**Closed by frigus02** 2022-06-06 15:24 UTC
Labels: bug
