### ISSUE TITLE
COOKIE not working

### ISSUE THREAD

**Issue by attatroll** [frigus02/RESTer#24] opened 2017-02-05 09:51 UTC
Using RESTer 2.0.1 with Firefox 51.0.1 (64 Bit) I try to send a PUT-Request and provide header COOKIE.

Checking with FIDDLER I can see that this header is NOT send by RESTer client.

All other header fields seem to work.

Is there a setting to enable COOKIE - headers? Or does RESTer deletes this header for any reason?

**Comment by frigus02** [comment] 2017-02-05 10:09
Hi. I can reproduce this and it is clearly a bug. RESTer does not delete the cookie header on purpose. I'm pretty sure it worked in earlier versions of RESTer as well. I need some time to figure out what is causing this.

**Comment by frigus02** [comment] 2017-02-05 16:39
Short update: The reason it's not working is because the Cookie header is blocked by Firefox and also by Chrome, when using either of [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) or [XHR](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest).

I found a way around this limitation, which is adding the cookie header in the [onBeforeSendHeaders](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onBeforeSendHeaders) event. This works great in Chrome and Firefox 53. But unfortunately I can't seem to convince Firefox 51 (current stable) to even fire this event.

**Comment by frigus02** [comment] 2017-02-05 17:46
Well, appearently there is a bug in Firefox, which will be fixed in version 52 only: https://bugzilla.mozilla.org/show_bug.cgi?id=1273138. So sadly I think I cannot make it work Firefox 51.

**Comment by frigus02** [comment] 2017-02-05 19:29
Good news. After thinking it through a couple more times, I found an easy solution. After a bit more testing I will upload a new version, which fixes this bug in all Firefox version including the current stable 51.

**Closed** 2017-03-05 13:54 UTC
Labels: bug
