### ISSUE TITLE
Can't save requests

### ISSUE THREAD

**Issue by dei79** [frigus02/RESTer#27] opened 2017-02-26 14:44 UTC
I try to save a request in Chrome and it does not work at all for some reason

![2017 15 38 16 2017-02-26 15-42-24](https://cloud.githubusercontent.com/assets/1666517/23340643/3ed7ca46-fc3a-11e6-9a02-7351c6885bd6.png)

I can't find any warnings or something else in the dev console. I guess it should appear on the left side? My Chrome Version is 56.0.2924.87 (64-bit) (Mac OS X).

**Comment by frigus02** [comment] 2017-02-26 17:31
Hi Dirk. That's actually a duplicate of #25. In this one text field you need to enter a collection and a title separated by a "/". This is far from obvious and will be improved in the next version.

E.g.: Demo / Demo Request

Tipp: You can create nested collections by adding more slashes: Demo / Sub / Demo Request.

**Comment by frigus02** [comment] 2017-03-20 17:33
Entering request title and collection is more clear now in version 2.2.0.

**Closed by frigus02** 2017-03-20 17:33 UTC
Labels: duplicate
